### ISSUE TITLE
$LSCOLORS and $LS_COLORS are overridden even if they are set beforehand

### ISSUE THREAD

**Issue by aroberts** [unixorn/warhol.plugin.zsh#11]
It took me a few minutes to track this down. I recognize that your recommended configuration is just to re-override these variables after your plugin is initialized, but some design choices I've made in how my dotfiles cascade on various hosts make that a little more awkward.

Would you be willing to perform an empty check before you override these environment vars with your personal configuration? If not, feel free to just close this out, and I'll continue with my fork, but I wonder if anyone else has had this issue.

**Comment by unixorn** [comment]
Not respecting existing color settings was definitely a bug, fixed.
