### ISSUE TITLE
ls's own colours are not used anymore

### ISSUE THREAD

**Issue by svenXY** [unixorn/warhol.plugin.zsh#25]
Hi,
according to https://github.com/garabik/grc/issues/36, one needs to either set 
` alias ls='grc --colour=auto ls --color=always'

or - as this post points out, one should be able to first set
`alias ls='ls --color -C'` before sourcing grc.zsh (i.e. before using warhol)

Unfortunately, the ls alias is removed before setting the ls() function:https://github.com/unixorn/warhol.plugin.zsh/blob/ab743a25d578825c28e61b240cfca69a5d7d2fa5/warhol.plugin.zsh#L22

Is there a way to get around this? Otherwise, while it is nice to have colors for the permissions, it lacks colors for directories, files, symlinks etc. which I find much more necessary.

I'd also be fine with not using warhol for ls while keeping it for the others, but as far as I can see, there is currently no means of disabling it for some of the commands, right?

**Comment by unixorn** [comment]
You can now disable wrapping on a per command basis by setting a `warhol_ignore_COMMANDNAME` var (content doesn't matter) in your `.zshrc` before you load the plugin.

If you're using [https://github.com/unixorn/zsh-quickstart-kit](https://github.com/unixorn/zsh-quickstart-kit), put a fragment file in `~/.zshrc.pre-plugins.d` with `export warhol_ignore_ls`.

**Comment by svenXY** [comment]
Thanks!
